### ISSUE TITLE
Frida-core no longer compiled with position independent flag. 

### ISSUE THREAD

**Issue by romainthomas** [frida/frida-core#211]
Hi! 
When I try to link ``libfrida-core.a`` **12.2.1** against a shared library, I get the following error from the linker:

```
arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: 
error: ../../frida-core/src/frida-core/libfrida-core.a(trees.c.o): 
requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
```
It looks like the lib is no longer compiled with fPIC. 

It worked well for frida ``12.0.8``

Thanks in advance.

**Comment by oleavr** [comment]
Hey!

Thanks for reporting. The code was built with `-fPIC` so that error isn't correct, or there's a bug in the NDK toolchain. Anyway, you should be linking with `-Wl,--gc-sections`, which both gives you smaller binaries and avoids this issue (because the faulty symbols aren't actually used). You probably also want some of the other Android linker flags from `releng/setup-env.sh`: `-Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -fuse-ld=gold -Wl,--fix-cortex-a8 -Wl,--icf=safe`

I won't be able to explore this rabbithole for now so if you're interested that would be awesome; but if not you should have a workaround :)

Cheers!
