### ISSUE TITLE
Frida for Genymotion

### ISSUE THREAD

**Issue by pentagramz** [frida/frida-core#78]
Is frida binary available for Genymotion.

Appreciate your support

**Comment by oleavr** [comment]
Hey,

No binaries are available, as it will require some development work to support this. You could build frida-server for x86/x86_64, however, the injector would have to be improved so it's able to detect targets with native ARM code, making it inject frida-agent.so for ARM instead of x86. This is not something I need myself so I don't think this will happen anytime soon, but if you're interested in helping out that would be awesome.

Cheers

**Comment by cse001** [comment]
We can find all the related frida-servers as well as other resources over here
https://github.com/frida/frida/releases
